apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Release.Name }}
spec:
  selector: 
    matchLabels:
      app: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: {{ .Values.port }}
          image: {{ .Values.image }}
          volumeMounts:
          - name: {{ .Release.Name }}
            mountPath: “/etc/newsecret”
            readOnly: true
          env:
            - name: ENVIRONMENT
              value: {{ .Values.environment }}
      imagePullSecrets:
      - name: dockerhub
      volumes:
        - name: {{ .Release.Name }}
          secret: 
            secretName: {{ .Release.Name }}



